services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile: 262144
    restart: unless-stopped
volumes:
    clickhouse_data: